---
- name: Find PHP
  find:
    paths: /usr/bin/
    patterns: ^php[0-9]+$
    use_regex: yes
    file_type: link
  register: php_binarys

- name: PHP Version String
  shell: "{{ item.path }} -v"
  register: php_version_string
  with_items: "{{ php_binarys.files }}"

- name: Current PHP Version
  shell: "echo '{{ php_version_string.results[0].stdout }}' | grep 'PHP [0-9]\\.[0-9]' -o | grep '[0-9]\\.[0-9]' -o"
  register: current_php_version

- name: Find Enable PHP Files
  find:
    paths: /etc/profile.d/
    patterns: enablephp*
    use_regex: no
  register: start_php_files

- name: Stop PHP starting
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ start_php_files.files }}"
  when: php_version != current_php_version.stdout

- name: Remove PHP
  yum:
    name: php*
    state: absent
  when: php_version != current_php_version.stdout
