---
- name: Stop PHP 5.6 starting
  shell: rm /etc/profile.d/enablephp56.sh
  ignore_errors: yes

- name: Stop PHP 7.2 starting
  shell: rm /etc/profile.d/enablephp72.sh
  ignore_errors: yes

- name: Remove PHP 5.6
  yum:
    name: php56*
    state: absent

- name: Remove PHP 7.2
  yum:
    name: php72*
    state: absent

- name: instal php
  yum:
    name: php73
    state: latest
    enablerepo: remi,remi-php73

- name: instal php-mbstring
  yum:
    name: php73-php-mbstring

- name: instal php-pdo
  yum:
    name: php73-php-pdo
    state: latest

- name: instal php-mbstring
  yum:
    name: php73-php-mysqlnd
    state: latest

- name: instal php-intl
  yum:
    name: php73-php-intl
    state: latest

- name: instal php-bcmath
  yum:
    name: php73-php-bcmath
    state: latest

- name: instal php-soap
  yum:
    name: php73-php-soap
    state: latest

- name: instal php-xdebug
  yum:
    name: php73-php-pecl-xdebug
    state: latest

- name: instal php-xml
  yum:
    name: php73-php-xml
    state: latest

- name: install php-zip
  yum:
    name: php73-php-zip
    state: latest

- name: instal php-memcache
  yum:
    name: php73-php-pecl-memcache
    state: latest

- name: instal php-memcached
  yum:
    name: php73-php-pecl-memcached
    state: latest

- name: instal php-fpm
  yum:
    name: php73-php-fpm
    state: latest
    enablerepo: remi,remi-php73

- name: set access log file
  file:
    state: directory
    path: /var/log/php-fpm
    mode: 0777

- name: php.ini file
  template:
    src: php.ini
    dest: /etc/opt/remi/php73/php.ini

- name: www.cnf file
  template:
    src: www.conf
    dest: /etc/opt/remi/php73/php-fpm.d/www.conf

- name: create php session directory
  file:
    state: directory
    path: /var/lib/php/session
    mode: 0777

- name: set access log file
  file:
    state: touch
    dest: /var/log/php-fpm/access.log
    mode: 0777

- name: set error log file
  file:
    state: touch
    dest: /var/log/php-fpm/error.log
    mode: 0777

- name: set slow log file
  file:
    state: touch
    dest: /var/log/php-fpm/slow.log
    mode: 0777

- name: start php-fpm
  service:
    name: php73-php-fpm
    state: started
    enabled: true

- name: enable php73
  template:
    src: enablephp73.sh
    dest: /etc/profile.d/enablephp73.sh
