---
- name: Create MySQL configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf

- name: Set custom mysqld configuration
  lineinfile:
    path: /etc/my.cnf
    line: '{{item.setting}}={{item.value}}'
    insertafter: '\[mysqld\]'
  with_items: "{{ mysqld | default([]) }}"

- name: Set custom mysqld_safe configuration
  lineinfile:
    path: /etc/my.cnf
    line: '{{item.setting}}={{item.value}}'
    insertafter: '\[mysqld_safe\]'
  with_items: "{{ mysqld_safe | default([]) }}"

- name: Set custom client configuration
  lineinfile:
    path: /etc/my.cnf
    line: '{{item.setting}}={{item.value}}'
    insertafter: '\[client\]'
  with_items: "{{ client | default([]) }}"

- name: Start the MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Temp Root Config
  shell: cat /var/log/mysqld.log | grep "temporary password" | cut -d ' ' -f 11
  register: temporary_mysql_password

- name: Create root Mysql configuration file
  template:
    src: my-default-root.cnf.j2
    dest: ~/.my.cnf

- name: testusers
  shell: mysql --connect-expired-password -e "ALTER USER USER() IDENTIFIED BY '#!SomeLongPassword1234'"
  when: (mysql_install_packages is defined and mysql_install_packages.changed)

- name: update mysql root password for all root accounts
  mysql_user: name={{ mysql_root_db_user }} host={{ item }} password={{ mysql_root_db_pass }} priv='*.*:ALL,GRANT' login_user='root' login_password='#!SomeLongPassword1234'
  with_items:
   - '%'
   - 127.0.0.1
   - ::1
   - 'localhost.localdomain'
   - localhost

- name: Create root user MySQL configuration file
  template:
    src: my-root.cnf.j2
    dest: ~/.my.cnf
  notify: restart mysql

- name: Create vagrant user MySQL configuration file
  become: true
  become_user: vagrant
  template:
    src: my-root.cnf.j2
    dest: ~/.my.cnf
  notify: restart mysql

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: localhost
    state: absent
    login_user: 'root'
    login_password: '#!SomeLongPassword1234'
