---
- name: install Zend PHP 5.6
  yum:
    name: "{{ packages }}"
    state: latest
    enablerepo: zendphp
  vars:
    packages:
    - php56zend-php-cli
    - php56zend-syspaths
    - php56zend-php-common
    - php56zend-php-bcmath
    - php56zend-php-bz2
    - php56zend-php-curl
    - php56zend-php-gd
    - php56zend-php-intl
    - php56zend-php-mbstring
    - php56zend-php-mcrypt
#    - php56zend-php-memcache #unavailable at present, not needed for bacpac?
#    - php56zend-php-memcached #unavailable at present, broken dependency chain (installs php56zend-php-pecl-memcached and requires php56zend-php-json), not needed for bacpac?
    - php56zend-php-mysql
    - php56zend-php-mysqli
    - php56zend-php-pcntl
#    - php56zend-php-pdo-mysql #unavailable at present (mysqlnd is available and installed as part of common)
    - php56zend-php-soap
    - php56zend-php-wddx
    - php56zend-php-xdebug
    - php56zend-php-xsl
    - php56zend-php-zip
    - php56zend-php-fpm
#    - php56zend-php-fpm-nginx-conf #unavailable at present

- name: set access log file
  file:
    state: directory
    path: /var/log/php-fpm
    mode: 0777

- name: php.ini file
  template:
    src: php.ini
    dest: /opt/zend/php56zend/root/etc/php.ini

- name: www.cnf file
  template:
    src: www.conf
    dest: /opt/zend/php56zend/root/etc/php-fpm.d/www.conf

- name: create php session directory
  file:
    state: directory
    path: /var/lib/php/session
    mode: 0777

- name: set access log file
  file:
    state: touch
    dest: /var/log/php-fpm/access.log
    mode: 0777
  changed_when: false

- name: set error log file
  file:
    state: touch
    dest: /var/log/php-fpm/error.log
    mode: 0777
  changed_when: false

- name: set slow log file
  file:
    state: touch
    dest: /var/log/php-fpm/slow.log
    mode: 0777
  changed_when: false

- name: start php-fpm
  service:
    name: php56zend-php-fpm
    state: started
    enabled: true

