---
- name: Find PHP
  find:
    paths: /usr/bin/
    patterns: ^php[0-9]+$
    use_regex: yes
    file_type: link
  register: php_binarys

- name: Install PHP Composer
  shell: "curl -sS https://getcomposer.org/installer | {{ item.path }} && /bin/mv -f /home/vagrant/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer"
  with_items: "{{ php_binarys.files }}"

- name: Install Global Phing
  become: true
  become_user: vagrant
  shell: "{{ item.path }} /usr/local/bin/composer global require phing/phing"
  with_items: "{{ php_binarys.files }}"
